version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1
  cloudrun: circleci/gcp-cloud-run@1.0.0
jobs:
  deploy_db:
    docker:
      - image: postgres:latest
    steps:
      - checkout
    environment:
      POSTGRES_USER: leankyr
      POSTGRES_PASSWORD: lalala
      POSTGRES_DB: CarsDB
      APP_DB_USER: leankyr
      APP_DB_PASS: lalala
      APP_DB_NAME: CarsDB
  deploy_node:
    docker:
      - image: node:16.13.2
    environment:
      HOST: "127.0.0.1"
      DB_PORT: 5432
      USER: "leankyr"
      PASS: "lalala"
      DB: "CarsDB"
      SERVER: "http://localhost:3000"
    working_directory:
      /usr/src/app
    steps:
      - checkout
      - run:
          command: npm install
      - run:
          command: |
           apt update
           apt install postgresql postgresql-contrib &&
           systemctl start postgresql.service
      - run:
          command: chmod +x ./src/database/migrations/01-init.sh
      - run:
          command: sh ./src/database/migrations/01-init.sh
      - run:
          command: |
            npm run test
workflows:
  build_test_deploy:
    jobs:
      - deploy_db
      - deploy_node