version: 2.1
jobs:
  build_db_and_node:
    docker:
      - image: cimg/postgres:12.8
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt upgrade
      - run: sudo apt install -y curl
      - run: sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - run: sudo chmod +x /usr/local/bin/docker-compose
      - run: service docker start
      - run: docker-compose up

workflows:
  build_test_deploy:
    jobs:
      - build_db_and_node
