version: 2.1
jobs:
  build:
#    working_directory: /usr/src/app/
    docker: # run the steps with Docker
      - image: cimg/node:16.13.2
    environment:
      HOST: "127.0.0.1"
      DB_PORT: 5432
      USER: "leankyr"
      PASS: "lalala"
      DB: "CarsDB"
      SERVER: "http://localhost:3000"
      POSTGRES_USER: leankyr
      POSTGRES_PASSWORD: lalala
      POSTGRES_DB: CarsDB
      APP_DB_USER: leankyr
      APP_DB_PASS: lalala
      APP_DB_NAME: CarsDB
    steps: # a collection of executable commands
      - checkout
      - run:
          name: Install project dependencies
          command: npm install
      - run:
          name: Update Repos
          command: sudo apt update
      - run:
          name: Install Postgres
          command: sudo apt -y install postgresql
      - run:
          name: Make file executable
          command: chmod +x ./src/database/migrations/01-init.sh
      - run:
          name: Create DB
          command: sh ./src/database/migrations/01-init.sh
      - run:
          name: Run tests
          command: npm test
