version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1
  cloudrun: circleci/gcp-cloud-run@1.0.0
jobs:
  build:
    docker:
      - image: cimg/postgres:12.8
      - image: cimg/node:16.14.2
    environment:
      HOST: "127.0.0.1"
      DB_PORT: 5432
      USER: "leankyr"
      PASS: "lalala"
      DB: "CarsDB"
      SERVER: "http://localhost:3000"
      POSTGRES_USER: leankyr
      POSTGRES_PASSWORD: lalala
      POSTGRES_DB: CarsDB
      APP_DB_USER: leankyr
      APP_DB_PASS: lalala
      APP_DB_NAME: CarsDB
    working_directory:
      /usr/src/app
    steps:
      - checkout
      - run:
          command: npm install
      - run:
          command: chmod +x ./src/database/migrations/01-init.sh
      - run:
          command: sh ./src/database/migrations/01-init.sh
      - run:
          command: |
            npm run test
workflows:
  build_test_deploy:
    jobs:
      - build