version: 2.1
jobs:
  build_db_and_node:
    docker:
      - image: cimg/postgres:12.8
    steps:
      - checkout
      - run: docker compose up

workflows:
  build_test_deploy:
    jobs:
      - build_db_and_node
