version: 2.1
jobs:
  build_db_and_node:
    docker:
      - image: cimg/postgres:12.8
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt upgrade
      - run: sudo apt install -y curl
      - run:  apt update && \
              sudo apt install -y curl apt-transport-https ca-certificates software-properties-common && \
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
              add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable" && \
              apt-cache policy docker-ce && \
              sudo apt update && sudo apt install -y docker-ce
      - run: sudo chmod +x /usr/local/bin/docker-compose
      - run: sudo service docker start
      - run: docker-compose up

workflows:
  build_test_deploy:
    jobs:
      - build_db_and_node
