version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1
  cloudrun: circleci/gcp-cloud-run@1.0.0
jobs:
  build_test:
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - run:
          command: |
            npm install
#      - run:
#          command: |
#            npm test
  build_push_image_cloud_run_mangaged:
    docker:
      - image: cimg/node:16.13.2

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build app binary and Docker image
          command: |
#            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV
#            echo ${GCP_PROJECT_KEY} | base64 --decode --ignore-garbage > /home/leankyr/IdeaProjects/CarsAPI/sa-private-key.json
            echo 'export GOOGLE_CLOUD_KEYS=$(cat $HOME/IdeaProjects/CarsAPI/sa-private-key.json)' >> $BASH_ENV
#            echo 'export TAG=${CIRCLE_SHA1}' >> $BASH_ENV
#            echo 'export IMAGE_NAME=$CIRCLE_PROJECT_REPONAME' >> $BASH_ENV && source $BASH_ENV
#            docker build -t eu.gcr.io/$GOOGLE_PROJECT_ID/$IMAGE_NAME -t eu.gcr.io/$GOOGLE_PROJECT_ID/$IMAGE_NAME:$TAG .
            docker build -t eu.gcr.io/cars-restful-api/node-app:latest .

      - gcp-gcr/gcr-auth:
          gcloud-service-key: GOOGLE_CLOUD_KEYS
          google-project-id: GOOGLE_PROJECT_ID
          google-compute-zone: GOOGLE_COMPUTE_ZONE
      - gcp-gcr/push-image:
          google-project-id: GOOGLE_PROJECT_ID
          registry-url: "eu.gcr.io"
          image: $IMAGE_NAME
      - cloudrun/deploy:
          platform: "managed"
          image: "eu.gcr.io/$GOOGLE_PROJECT_ID/$IMAGE_NAME"
          service-name: "orb-gcp-cloud-run"
          region: $GOOGLE_COMPUTE_ZONE
          unauthenticated: true
workflows:
  build_test_deploy:
    jobs:
      - build_test
      - build_push_image_cloud_run_mangaged:
          requires:
            - build_test