version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16.13.2
    steps:
      - checkout
      - run:
          command: |
            npm init
      - run:
          command: |
            npm install
      - run:
          command: |
            npm test
