version: 2.1
jobs:
  build_db_and_node:
    docker:
      - image: cimg/postgres:12.8
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt upgrade
      - run: sudo apt install -y curl
      - run:
      name: Install Docker Compose
      environment:
        COMPOSE_VERSION: '1.29.2'
      command: |
        curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
        chmod +x ~/docker-compose
        sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run: sudo chmod +x /usr/local/bin/docker-compose
      - run: sudo service docker start
      - run: docker-compose up

workflows:
  build_test_deploy:
    jobs:
      - build_db_and_node
